apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  revisionHistoryLimit: 2   # 👈 Sirf latest 2 ReplicaSet rakhega
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/itexperts-sanju/myapp:63
        ports:
        - containerPort: 80
