apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Flask app port
      nodePort: 30080   # External port
